// Generated by CoffeeScript 1.7.1
(function() {
  var Book,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Book = (function(_super) {
    __extends(Book, _super);

    Book.extend(Spine.Events);

    Book.checkout = function(isbn) {
      this.trigger('loading', true, isbn);
      return $.ajax("/books/" + isbn).then(function(data) {
        Book.trigger('loading', false, isbn);
        return new Book(data);
      }).promise();
    };

    function Book(data) {
      var key, value;
      for (key in data) {
        value = data[key];
        this[key] = value;
      }
    }

    return Book;

  })(Spine.Module);

  window.Book = Book;

}).call(this);
