// Generated by CoffeeScript 1.7.1
(function() {
  beforeEach(function() {
    return this.addMatchers({
      toHaveBound: function(event, method) {
        return (this.actual._callbacks[event] || []).indexOf(method) > -1;
      }
    });
  });

}).call(this);
